# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines
steps:
- task: Docker@0
  displayName: buildAndPush
  inputs:
    imageName: 'freescout'

- task: AmazonWebServices.aws-vsts-tools.ECRPushImage.ECRPushImage@1
  displayName: 'Push Image: '
  inputs:
    awsCredentials: 'AWS-Azure-User'
    regionName: 'ap-southeast-2'
    sourceImageName: 'freescout'
    repositoryName: 'freescout'

- task: AmazonWebServices.aws-vsts-tools.AWSCLI.AWSCLI@1
  displayName: 'AWS CLI: ecs'
  inputs:
    awsCredentials: 'AWS-Azure-User'
    regionName: 'ap-southeast-2'
    awsCommand: ecs
    awsSubCommand: 'update-service'
    awsArguments: '--cluster TestCluster --service freescout --force-new-deployment'
    failOnStandardError: false

