# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'AWS-Azure-User'
    regionName: 'ap-southeast-2'
    imageSource: 'imagename'
    sourceImageName: 'freescout'
    repositoryName: 'freescout'
- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS-Azure-User'
    regionName: 'ap-southeast-2'
    awsCommand: 'ecs'
    awsSubCommand: '--cluster DevCluster --service freescout --force-new-deployment'
